BoardGameStore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('store/', include('store.urls')),
    path('cart/', include('cart.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    path('', cart_detail, name='cart_detail'),
    path('add/<int:item_id>', cart_add, name='cart_add'),
    path('remove/<int:item_id>', cart_remove, name='cart_remove'),
    path('clear/', cart_clear, name='cart_clear'),
]

store/models.py
from django.db import models
from django.urls import reverse


class Game(models.Model):
    title = models.CharField(max_length=150, verbose_name='Название')
    short_description = models.TextField(blank=True, null=True, verbose_name='Краткое описание')
    description = models.TextField(blank=True, null=True, verbose_name='Полное описание')
    rules = models.TextField(blank=True, null=True, verbose_name='Правила игры')
    price = models.IntegerField(verbose_name='Цена')
    date_create = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    date_update = models.DateTimeField(auto_now=True, verbose_name='Дата обновления')
    image = models.ImageField(upload_to='image/game/', blank=True, null=True, verbose_name='Изображение')
    exist = models.BooleanField(default=True, verbose_name='Наличие')

    objects = models.Manager()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('game_detail', kwargs={'game_id': self.pk})

    class Meta:
        verbose_name = 'Игру'
        verbose_name_plural = 'Игры'
        ordering = ['title', 'id']

templates/base.html
{% load static %}

<!doctype html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
        {% block title %}{% endblock %}
    </title>
    {% block link %}
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.4/font/bootstrap-icons.css">
        <link rel="stylesheet" href="{% static 'store/css/style.css' %}">
    {% endblock %}
</head>
<body class="bg-body-tertiary">
{% block body %}
{% endblock %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

templates/main.html
{% extends 'base.html' %}

{% load dice %} {# Импорт рандомайзера для кубиков #}

{% block title %}{% endblock %}

{% block body %}
    <header class="mb-4 bg-white pb-3">
        <div class="container p-0 p-sm-auto" style="max-width: 60rem;">
            {% include 'inc/_header.html' %}
            <div class="container p-sm-0">
                {% block x %}
                    <div class="border-top border-bottom py-3">
                        <div class="row justify-content-center justify-content-sm-between align-items-center">
                            <div class="text-primary col-auto"> {# Блок с кубиками #}
                                <h1>
                                    <i id="dice2" class="bi-dice-{% dice_roll %}"></i>
                                    <i id="dice1" class="bi-dice-{% dice_roll %}"></i>
                                    {% block current_page %}{% endblock %}
                                </h1>
                            </div>
                            {% if perms.games.change_game %}
                                <div class="col-auto">
                                    {% block permission %}{% endblock %} {# Блок с правами доступа #}
                                </div>
                            {% endif %}
                        </div>
                    </div>
                {% endblock %}
            </div>
        </div>
    </header>
    <div class="container p-0 p-sm-auto" style="max-width: 60rem;">
        <main>
            {% block content %}{% endblock %}
        </main>
        <footer>
            {% include 'inc/_footer.html' %}
        </footer>
    </div>
{% endblock %}